---
apiVersion: v1
kind: ConfigMap
metadata:
  name: citadel-config
  namespace: industries
data:
  config.json: |
    {
      "database": {
        "path": "/app/data/citadel.db",
        "schema": "./schema/model.sql"
      },
      "server": {
        "port": "8080"
      }
    }
