---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: citadel
  namespace: industries
  labels:
    app: citadel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citadel
  template:
    metadata:
      labels:
        app: citadel
    spec:
      containers:
        - name: citadel
          image: julianone/citadel:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
