---
apiVersion: v1
kind: Service
metadata:
  name: citadel
  namespace: industries
spec:
  selector:
    app: citadel
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
